"""empty message

Revision ID: b24459b4682e
Revises: 79b1118b1774
Create Date: 2016-03-13 18:47:36.210028

"""

# revision identifiers, used by Alembic.
revision = 'b24459b4682e'
down_revision = '79b1118b1774'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onlineinfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('device', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onlineinfo_device'), 'onlineinfo', ['device'], unique=True)
    op.create_index(op.f('ix_onlineinfo_username'), 'onlineinfo', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onlineinfo_username'), table_name='onlineinfo')
    op.drop_index(op.f('ix_onlineinfo_device'), table_name='onlineinfo')
    op.drop_table('onlineinfo')
    ### end Alembic commands ###
