"""empty message

Revision ID: da059d7f8f53
Revises: bd39533db845
Create Date: 2016-03-13 01:05:25.596766

"""

# revision identifiers, used by Alembic.
revision = 'da059d7f8f53'
down_revision = 'bd39533db845'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
