"""empty message

Revision ID: efc41e83f849
Revises: b24459b4682e
Create Date: 2016-03-13 21:45:13.299090

"""

# revision identifiers, used by Alembic.
revision = 'efc41e83f849'
down_revision = 'b24459b4682e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_onlineinfo_device', table_name='onlineinfo')
    op.create_index(op.f('ix_onlineinfo_device'), 'onlineinfo', ['device'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onlineinfo_device'), table_name='onlineinfo')
    op.create_index('ix_onlineinfo_device', 'onlineinfo', ['device'], unique=1)
    ### end Alembic commands ###
