"""empty message

Revision ID: fcf6d6e05b3a
Revises: efc41e83f849
Create Date: 2016-03-14 22:01:26.733387

"""

# revision identifiers, used by Alembic.
revision = 'fcf6d6e05b3a'
down_revision = 'efc41e83f849'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weibo_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_weibo_id'), 'users', ['weibo_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_weibo_id'), table_name='users')
    op.drop_column('users', 'weibo_id')
    ### end Alembic commands ###
